"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import mysql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sub_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ym', sa.String(length=7), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=False),
    sa.Column('allocation', sa.String(length=2), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('last_month_fy', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('for_month', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('to_month_fy', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('opening_running', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('closing_running', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('opening_source', sa.String(length=10), nullable=False),
    sa.Column('running_estimated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ym', 'code')
    )
    op.create_index('ix_bsa_alloc', 'balance_sub_allocations', ['allocation', 'ym'], unique=False)
    op.create_table('balance_uwids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ym', sa.String(length=7), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=False),
    sa.Column('allocation', sa.String(length=2), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('head', sa.String(length=8), nullable=False),
    sa.Column('uwid', sa.String(length=50), nullable=False),
    sa.Column('last_month_fy', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('for_month', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('to_month_fy', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('opening_running', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('closing_running', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ym', 'head', 'uwid')
    )
    op.create_index('ix_bu_code', 'balance_uwids', ['code', 'ym'], unique=False)
    op.create_index('ix_bu_uwid', 'balance_uwids', ['uwid', 'ym'], unique=False)
    op.create_table('months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ym', sa.String(length=7), nullable=False),
    sa.Column('au', sa.String(length=10), nullable=False),
    sa.Column('reports_ready_at', sa.DateTime(), nullable=True),
    sa.Column('separated_at', sa.DateTime(), nullable=True),
    sa.Column('documents_ready_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ym')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('uwid_master',
    sa.Column('uwid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uwid')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ym', sa.String(length=7), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_ym', 'events', ['ym', 'created_at'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary().with_variant(mysql.LONGBLOB(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_month_kind', 'files', ['month_id', 'kind', 'reference'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opening_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ym', sa.String(length=7), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('last_month_fy', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('opening_running', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('running_confirmed', sa.Boolean(), nullable=False),
    sa.Column('entered_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ym', 'code')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('suspense_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.Column('allocation', sa.String(length=2), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('head', sa.String(length=8), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('co6', sa.String(length=50), nullable=True),
    sa.Column('co7', sa.String(length=50), nullable=True),
    sa.Column('book_date', sa.String(length=20), nullable=True),
    sa.Column('party_name', sa.Text(), nullable=True),
    sa.Column('bill_desc', sa.Text(), nullable=True),
    sa.Column('debit_text', sa.String(length=40), nullable=True),
    sa.Column('credit_text', sa.String(length=40), nullable=True),
    sa.Column('debit', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('credit', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('spu', sa.String(length=100), nullable=True),
    sa.Column('contract_id', sa.String(length=100), nullable=True),
    sa.Column('tan_number', sa.String(length=50), nullable=True),
    sa.Column('uwid', sa.String(length=50), nullable=True),
    sa.Column('is_jv', sa.Boolean(), nullable=False),
    sa.Column('is_sys_generated', sa.Boolean(), nullable=False),
    sa.Column('in_daybook', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entries_co6', 'suspense_entries', ['co6'], unique=False)
    op.create_index('ix_entries_month_alloc', 'suspense_entries', ['month_id', 'allocation', 'code'], unique=False)
    op.create_index('ix_entries_uwid', 'suspense_entries', ['uwid'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co6_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_id', 'kind', 'number')
    )
    op.create_table('month_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.Column('allocation', sa.String(length=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('via', sa.String(length=10), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=True),
    sa.Column('heads', sa.Integer(), nullable=True),
    sa.Column('entries', sa.Integer(), nullable=True),
    sa.Column('original_file_id', sa.Integer(), nullable=True),
    sa.Column('converted_file_id', sa.Integer(), nullable=True),
    sa.Column('rows', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converted_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_id', 'allocation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('month_allocations')
    op.drop_table('co6_items')
    op.drop_table('user_scopes')
    op.drop_table('user_roles')
    op.drop_index('ix_entries_uwid', table_name='suspense_entries')
    op.drop_index('ix_entries_month_alloc', table_name='suspense_entries')
    op.drop_index('ix_entries_co6', table_name='suspense_entries')
    op.drop_table('suspense_entries')
    op.drop_table('role_permissions')
    op.drop_table('opening_balances')
    op.drop_table('jobs')
    op.drop_index('ix_files_month_kind', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_events_ym', table_name='events')
    op.drop_table('events')
    op.drop_table('uwid_master')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('months')
    op.drop_index('ix_bu_uwid', table_name='balance_uwids')
    op.drop_index('ix_bu_code', table_name='balance_uwids')
    op.drop_table('balance_uwids')
    op.drop_index('ix_bsa_alloc', table_name='balance_sub_allocations')
    op.drop_table('balance_sub_allocations')
    # ### end Alembic commands ###
